spring.application.name=saasapp

# ========== Datasource ==========
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ========== Flyway ==========
spring.flyway.enabled=${SPRING_FLYWAY_ENABLED:true}
spring.flyway.locations=classpath:db/migration

# ========== JPA / Hibernate ==========
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ========== JWT ==========
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration=${APP_JWT_EXPIRATION:86400000}

# ========== Logging ==========
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.springframework.security=DEBUG

# ========== Actuator ==========
management.endpoints.web.exposure.include=health,info,metrics,httpexchanges,heapdump
management.endpoint.heapdump.enabled=true
management.endpoint.metrics.enabled=true

# ========== Swagger ==========
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true